name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Setup .NET
        uses: actions/setup-dotnet@v1
        with:
          dotnet-version: '8.0.x'

      - name: Update wwwroot/index.html
        run: |
          sed -i 's|<base href="/" />|<base href="/SkillSync-AI/" />|g' ResumeAnalyzer.Client/wwwroot/index.html

      - name: Publish
        run: dotnet publish ResumeAnalyzer.Client/ResumeAnalyzer.Client.csproj -c Release -o release --nologo

      - name: Deploy
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          branch: gh-pages
          folder: release/wwwroot
          clean: true 